<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="pushpa-PC" name="com.create4.execution.Allrole_menus_TS_128" tests="5" failures="0" timestamp="18 Apr 2018 15:21:22 GMT" time="62.237" errors="1">
  <testcase name="CRe4_602_603_604_605" time="12.765" classname="com.create4.execution.Allrole_menus_TS_128"/>
  <testcase name="CRe4_606_607" time="7.764" classname="com.create4.execution.Allrole_menus_TS_128">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.global.methods.GlobalMethods.Member1Login(GlobalMethods.java:301)
	at com.create4.scenarios.TS_128.CRe4_606_607(TS_128.java:529)
	at com.create4.execution.Allrole_menus_TS_128.CRe4_606_607(Allrole_menus_TS_128.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- CRe4_606_607 -->
  <testcase name="CRe4_596_597" time="11.655" classname="com.create4.execution.Allrole_menus_TS_128"/>
  <testcase name="CRe4_600_601" time="16.683" classname="com.create4.execution.Allrole_menus_TS_128"/>
  <testcase name="CRe4_598_99" time="13.370" classname="com.create4.execution.Allrole_menus_TS_128"/>
</testsuite> <!-- com.create4.execution.Allrole_menus_TS_128 -->
